# Numpy Mathematics

In [1]:
import numpy as np

In [2]:
# element wise operation

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [3]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [4]:
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [5]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [6]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [7]:
# Matrix Multiplication
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [8]:
print(np.sum(x,axis=0))

[4 6]


In [9]:
print(np.sum(x,axis=1))

[3 7]


In [10]:
print(np.min(x))

1


In [11]:
print(np.max(x))

4


In [12]:
print(x.T)

[[1 3]
 [2 4]]


## Statistics

In [13]:
x = np.array([23,40,6,74,38,1,70])

In [14]:
np.mean(x)

36.0

In [15]:
np.median(x)

38.0

In [16]:
from scipy import stats

In [17]:
mode = stats.mode(x)
print(mode[0])

[1]


In [18]:
np.std(x)

26.49528259898354