# Numpy

Most powerful numerical processing library in python. Array oriented comuting.

In [1]:
# creating a simple array in numpy

import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr = np.array([1,2,3,4])
print(arr)

# print number of dimensions
print(arr.ndim)

# print shape
print(arr.shape)

# print length
print(len(arr))

# print datatype
print(arr.dtype)

# print item size in byte of each element
print(arr.itemsize)

[1 2 3 4]
1
(4,)
4
int32
4


In [8]:
arr =  np.array([[1,2,3],[4,5,6]])
print(arr)

# print number of dimensions
print(arr.ndim)

# print shape
print(arr.shape)

# print length
print(len(arr))

# print datatype
print(arr.dtype)

# print item size in byte of each element
print(arr.itemsize)

# print diagonal element
print(np.diag(arr))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2
int32
4
[1 5]


## Functions for creating array

In [9]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
arr = np.eye(3,2)
print(arr)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [13]:
arr  = np.random.random((2,2))
print(arr)

[[0.02359437 0.09243401]
 [0.25807779 0.76776057]]


## Numpy Indexing

In [15]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
print(arr[2])

2


In [17]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [18]:
print(arr[1,2])

6


In [20]:
arr[1,2] = 99
print(arr)

[[ 1  2  3]
 [ 4  5 99]]


## Numpy slicing

In [21]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
print(arr[::2])
print(arr[1:4])
print(arr[0:-4])

[0 2 4 6 8]
[1 2 3]
[0 1 2 3 4 5]


In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print(arr[:2,1:3])

[[2 3]
 [5 6]]


In [25]:
print(arr[1:2,:])

[[4 5 6]]


In [27]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [28]:
print(arr[[0,1,2],[0,1,0]])

[1 4 5]
